const gameData = [
    {
        gameId: 12314,
        gamePlayerStats: [
    {
        playerId: 1,
        playerName: "Michael borohov",
        points: 17,
        rebounds: 4,
        assists: 2,
        steals: 0,
        blocks: 0,
        threePointsAtt: 2,        
        threePointsMade: 2,
        threePointPct: 100,
        fieldGoalAtt: 14,
        fieldGoalMade: 7,
        fieldGoalPct: 50,
        freeThrowAtt: 1,
        freeThrowMade: 4,
        freeThrowPct: 25,
        turnover:1

    },
    {
        playerId: 2,
        playerName: "Amir Toueg",
        points: 0,
        rebounds: 2,
        assists: 2,
        steals: 3,
        blocks: 0,
        threePointsAtt: "n/a",        
        threePointsMade: 0,
        threePointPct: "n/a",
        fieldGoalAtt: 6,
        fieldGoalMade: 0,
        fieldGoalPct: 0,
        freeThrowAtt: 0,
        freeThrowMade: 0,
        freeThrowPct: 0,
        turnover:3
    },
    {
        playerId: 3,
        playerName: "Amir Golan",
        points: 4,
        rebounds: 5,
        assists: 4,
        steals: 3,
        blocks: 0,
        threePointsAtt: "n/a",        
        threePointsMade: 0,
        threePointPct: "n/a",
        fieldGoalAtt: 5,
        fieldGoalMade: 2,
        fieldGoalPct: 40,
        freeThrowAtt: 0,
        freeThrowMade: 0,
        freeThrowPct: 0,
        turnover:1
    },
    {
        playerId: 4,
        playerName: "Tzahi Greenberg",
        points: 9,
        rebounds: 2,
        assists: 2,
        steals: 0,
        blocks: 0,
        threePointsAtt: "n/a",        
        threePointsMade: 3,
        threePointPct: "n/a",
        fieldGoalAtt: 6,
        fieldGoalMade: 3,
        fieldGoalPct: 50,
        freeThrowAtt: 0,
        freeThrowMade: 0,
        freeThrowPct: 0,
        turnover:2
    },
    {
        playerId: 5,
        playerName: "Amos Bercovich",
        points: 0,
        rebounds: 1,
        assists: 1,
        steals: 0,
        blocks: 0,
        threePointsAtt: "n/a",        
        threePointsMade: 0,
        threePointPct: "n/a",
        fieldGoalAtt: 6,
        fieldGoalMade: 0,
        fieldGoalPct: 0,
        freeThrowAtt: 0,
        freeThrowMade: 0,
        freeThrowPct: 0,
        turnover:1
    },
    {
        playerId: 6,
        playerName: "Iden Oren",
        points: 14,
        rebounds: 7,
        assists: 2,
        steals: 1,
        blocks: 0,
        threePointsAtt: "n/a",        
        threePointsMade: 2,
        threePointPct: "n/a",
        fieldGoalAtt: 9,
        fieldGoalMade: 5,
        fieldGoalPct: 55.56,
        freeThrowAtt: 2,
        freeThrowMade: 2,
        freeThrowPct: 100,
        turnover:1
    },
    {
        playerId: 7,
        playerName: "Gilad Aidenberg",
        points: 5,
        rebounds: 3,
        assists: 1,
        steals: 2,
        blocks: 0,
        threePointsAtt: "n/a",        
        threePointsMade: 0,
        threePointPct: "n/a",
        fieldGoalAtt: 9,
        fieldGoalMade: 2,
        fieldGoalPct: 22.22,
        freeThrowAtt: 2,
        freeThrowMade: 1,
        freeThrowPct: 50,
        turnover:2
    },
    {
        playerId: 8,
        playerName: "Eyal Uriel",
        points: 7,
        rebounds: 4,
        assists: 3,
        steals: 0,
        blocks: 0,
        threePointsAtt: "n/a",        
        threePointsMade: 1,
        threePointPct: "n/a",
        fieldGoalAtt: 4,
        fieldGoalMade: 2,
        fieldGoalPct: 50,
        freeThrowAtt: 2,
        freeThrowMade: 2,
        freeThrowPct: 100,
        turnover:1
    },
    {
        playerId: 9,
        playerName: "Gadi Berqowitz*",
        points: 0,
        rebounds: 0,
        assists: 0,
        steals: 0,
        blocks: 0,
        threePointsAtt: "n/a",        
        threePointsMade: 0,
        threePointPct: "n/a",
        fieldGoalAtt: 0,
        fieldGoalMade: 0,
        fieldGoalPct: 0,
        freeThrowAtt: 0,
        freeThrowMade: 0,
        freeThrowPct: 0,
        turnover:0
    },
    {
        playerId: 10,
        playerName: "Itay Ventura*",
        points: 0,
        rebounds: 0,
        assists: 0,
        steals: 0,
        blocks: 0,
        threePointsAtt: "n/a",        
        threePointsMade: 0,
        threePointPct: "n/a",
        fieldGoalAtt: 0,
        fieldGoalMade: 0,
        fieldGoalPct: 0,
        freeThrowAtt: 0,
        freeThrowMade: 0,
        freeThrowPct: 0,
        turnover:0
    }]
    }
]; 
 
export  default gameData;